export enum CONSTANTS {
  MAX_TRIES = 10,
  PLAYER_WIN_MSG = "YOU WIN!!!",
  COMPUTER_WIN_MSG = "COMPUTER WIN!!!",
  COMPUTER_ONE_WIN_MSG = "COMPUTER ONE WIN!!!",
  COMPUTER_TWO_WIN_MSG = "COMPUTER TWO WIN!!!",
}
