export const CONSTANTS = {
  MAX_TRIES: 10,
  PLAYER_WIN_MSG: "YOU WIN!!!",
  DRAW: "IT'S A TIE",
  COMPUTER_WIN_MSG: "COMPUTER WIN!!!",
  COMPUTER_ONE_WIN_MSG: "COMPUTER ONE WIN!!!",
  COMPUTER_TWO_WIN_MSG: "COMPUTER TWO WIN!!!",
  GAME_MODE_USER: "user",
  GAME_MODE_COMPUTER: "computer",
};
